require("dotenv").config();
const express = require("express");
const cors = require("cors");
const path = require("path");
const app = express();
app.use(cors());
app.use(express.json());
app.use("/users", require("./routes/users"));
app.use("/livestock", require("./routes/livestock"));
app.use("/market", require("./routes/market"));
app.use("/finance", require("./routes/finance"));
app.use("/weather", require("./routes/weather"));
app.use("/ai", require("./routes/ai"));
app.use("/alerts", require("./routes/alerts"));
app.use("/transport", require("./routes/transport"));
app.use("/map", require("./routes/map"));
app.get("/dashboard", (req, res) => { res.sendFile(path.join(__dirname, "dashboard.html")); });
app.get("/", (req, res) => { res.json({ message: "Malchin Super App", version: "2.0" }); });
app.listen(5000, "0.0.0.0", () => { console.log("Malchin backend v2.0 running on port 5000"); });