const express = require("express");
const router = express.Router();
const axios = require("axios");
const API_KEY = process.env.OPENWEATHER_API_KEY || "";
const COORDS = { "Ulaanbaatar": { lat: 47.92, lon: 106.91 }, "Arkhangai": { lat: 47.86, lon: 100.72 }, "Khuvsgul": { lat: 49.39, lon: 99.73 }, "Umnugobi": { lat: 43.57, lon: 104.43 }, "Tuv": { lat: 47.71, lon: 106.95 }, "Dornod": { lat: 47.32, lon: 115.79 }, "Khovd": { lat: 48.01, lon: 91.64 }, "Khentii": { lat: 47.32, lon: 109.65 }, "Bayankhongor": { lat: 46.19, lon: 100.72 }, "Zavkhan": { lat: 48.26, lon: 96.07 }, "Selenge": { lat: 49.89, lon: 106.18 }, "Bulgan": { lat: 48.81, lon: 103.53 }, "Uvs": { lat: 49.98, lon: 92.07 }, "Bayan-Ulgii": { lat: 48.97, lon: 89.96 }, "Dundgobi": { lat: 45.76, lon: 106.26 }, "Uvurkhangai": { lat: 46.26, lon: 102.78 }, "Sukhbaatar": { lat: 46.68, lon: 113.38 } };
const MN_TO_EN = { "Улаанбаатар": "Ulaanbaatar", "Архангай": "Arkhangai", "Хөвсгөл": "Khuvsgul", "Өмнөговь": "Umnugobi", "Төв": "Tuv", "Дорнод": "Dornod", "Ховд": "Khovd", "Хэнтий": "Khentii", "Баянхонгор": "Bayankhongor", "Завхан": "Zavkhan", "Сэлэнгэ": "Selenge", "Булган": "Bulgan", "Увс": "Uvs", "Баян-Өлгий": "Bayan-Ulgii", "Дундговь": "Dundgobi", "Өвөрхангай": "Uvurkhangai", "Сүхбаатар": "Sukhbaatar" };
function dzudRisk(t, w, s) { let sc = 0; if (t < -30) sc += 4; else if (t < -20) sc += 3; else if (t < -10) sc += 2; else if (t < 0) sc += 1; if (w > 15) sc += 3; else if (w > 10) sc += 2; else if (w > 5) sc += 1; if (s > 30) sc += 3; else if (s > 15) sc += 2; else if (s > 5) sc += 1; if (sc >= 8) return "very_high"; if (sc >= 6) return "high"; if (sc >= 4) return "medium"; return "low"; }
async function fetchWeather(aimag) { const c = COORDS[aimag]; if (!c || !API_KEY) return null; try { const r = await axios.get("https://api.openweathermap.org/data/2.5/weather?lat=" + c.lat + "&lon=" + c.lon + "&appid=" + API_KEY + "&units=metric&lang=mn"); const d = r.data; const snow = d.snow ? d.snow["1h"] || 0 : 0; return { aimag, temp: Math.round(d.main.temp), feels_like: Math.round(d.main.feels_like), temp_min: Math.round(d.main.temp_min), temp_max: Math.round(d.main.temp_max), wind: d.wind.speed, humidity: d.main.humidity, condition: d.weather[0].main, description: d.weather[0].description, icon: d.weather[0].icon, snow, dzud_risk: dzudRisk(d.main.temp, d.wind.speed, snow), source: "openweathermap" }; } catch (e) { console.error("Weather error:", e.response ? e.response.data.message : e.message); return null; } }
async function fetchForecast(aimag) { const c = COORDS[aimag]; if (!c || !API_KEY) return []; try { const r = await axios.get("https://api.openweathermap.org/data/2.5/forecast?lat=" + c.lat + "&lon=" + c.lon + "&appid=" + API_KEY + "&units=metric&lang=mn&cnt=40"); const daily = {}; r.data.list.forEach(item => { const date = item.dt_txt.split(" ")[0]; if (!daily[date]) daily[date] = { temps: [], winds: [], conditions: [], date }; daily[date].temps.push(item.main.temp); daily[date].winds.push(item.wind.speed); daily[date].conditions.push(item.weather[0].main); }); return Object.values(daily).slice(0, 5).map((d, i) => ({ day: i + 1, date: d.date, temp_min: Math.round(Math.min(...d.temps)), temp_max: Math.round(Math.max(...d.temps)), wind: Math.round(Math.max(...d.winds)), condition: d.conditions[Math.floor(d.conditions.length / 2)], dzud_risk: dzudRisk(Math.min(...d.temps), Math.max(...d.winds), 0) })); } catch (e) { return []; } }
router.get("/:aimag", async (req, res) => { const mnName = req.params.aimag; const enName = MN_TO_EN[mnName] || mnName; if (API_KEY) { const current = await fetchWeather(enName); if (current) { current.aimag = mnName; const forecast = await fetchForecast(enName); return res.json({ ...current, forecast }); } } res.json({ aimag: mnName, source: "demo", temp: -3, wind: 2, humidity: 65, condition: "Cloudy", dzud_risk: "low", forecast: [{ day: 1, date: "Маргааш", temp_min: -8, temp_max: -1, wind: 3, condition: "Cloudy", dzud_risk: "low" }, { day: 2, date: "2 дахь өдөр", temp_min: -12, temp_max: -4, wind: 5, condition: "Snow", dzud_risk: "medium" }, { day: 3, date: "3 дахь өдөр", temp_min: -15, temp_max: -6, wind: 8, condition: "Snow", dzud_risk: "medium" }, { day: 4, date: "4 дахь өдөр", temp_min: -10, temp_max: -2, wind: 4, condition: "Clear", dzud_risk: "low" }, { day: 5, date: "5 дахь өдөр", temp_min: -7, temp_max: 1, wind: 2, condition: "Clear", dzud_risk: "low" }] }); });
router.get("/", async (req, res) => { if (API_KEY) { try { const results = await Promise.all(Object.keys(COORDS).slice(0, 8).map(a => fetchWeather(a))); return res.json(results.filter(r => r)); } catch (e) {} } res.json([{ aimag: "Tuv", source: "demo", temp: -3, condition: "Cloudy", dzud_risk: "low" }]); });
module.exports = router;